version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - thelper
    - tparallel
    - unused
    - varnamelen
    - wsl_v5

formatters:
  enable:
    - gofmt

issues:
  exclude-use-default: false
