name: Feature request
description: Propose a new algorithm, API, or development enhancement.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What limitation or user need does this address?
      placeholder: The current package/API does not...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the API or behavior you want.
      placeholder: Add package/function/type...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches or why existing APIs are not enough.
  - type: textarea
    id: impact
    attributes:
      label: Scope and impact
      description: Compatibility, performance, and testing implications.
