package effectchain

// builtInDescriptors keeps canonical parameter names adjacent to their bounds.
//
//nolint:funlen
func builtInDescriptors(sampleRate float64) []Descriptor {
	return []Descriptor{
		descriptor(
			"chorus", "Chorus", "Modulation", "generic",
			integerParameter("stages", 3, 1, 6),
			numberParameter("mix", 0.18, 0, 1),
			numberParameter("depth", 0.003, 0, 0.01),
			numberParameter("speedHz", 0.35, 0.05, 5),
		),
		descriptor(
			"flanger", "Flanger", "Modulation", "generic",
			numberParameter("rateHz", 0.25, 0.05, 5),
			numberParameter("baseDelay", 0.001, 0.0001, 0.01),
			numberParameter("depth", 0.0015, 0, 0.0099),
			numberParameter("feedback", 0.25, -0.99, 0.99),
			numberParameter("mix", 0.5, 0, 1),
		),
		descriptor(
			"ringmod", "Ring modulation", "Modulation", "generic",
			numberParameter("carrierHz", 440, 1, sampleRate*0.49),
			numberParameter("mix", 1, 0, 1),
		),
		descriptor(
			"bitcrusher", "Bitcrusher", "Distortion", "generic",
			integerParameter("downsample", 4, 1, 256),
			numberParameter("bitDepth", 8, 1, 32),
			numberParameter("mix", 1, 0, 1),
		),
		descriptor(
			"distortion", "Distortion", "Distortion", "generic",
			numberParameter("drive", 1.8, 0.01, 20),
			numberParameter("mix", 1.0, 0, 1),
			numberParameter("output", 1.0, 0, 4),
			numberParameter("clip", 1.0, 0.05, 1),
			numberParameter("shape", 0.5, 0, 1),
			numberParameter("bias", 0, -1, 1),
			enumParameter("mode", "softclip", "softclip", "hardclip", "tanh", "waveshaper1", "waveshaper2", "waveshaper3", "waveshaper4", "waveshaper5", "waveshaper6", "waveshaper7", "waveshaper8", "saturate", "saturate2", "softsat", "chebyshev"),
			enumParameter("approx", "exact", "exact", "polynomial"),
		),
		descriptor(
			"dist-cheb", "Chebyshev distortion", "Distortion", "generic",
			integerParameter("order", 3, 1, 16),
			booleanParameter("invert", 0),
			booleanParameter("dcBypass", 0),
			numberParameter("drive", 1.0, 0.01, 20),
			numberParameter("mix", 1.0, 0, 1),
			numberParameter("output", 1.0, 0, 4),
			numberParameter("gain", 1.0, 0, 4),
			enumParameter("approx", "exact", "exact", "polynomial"),
			enumParameter("harmonic", "all", "all", "odd", "even"),
			numberParameter("w1", 0, -4, 4),
			numberParameter("w2", 0, -4, 4),
			numberParameter("w3", 0, -4, 4),
			numberParameter("w4", 0, -4, 4),
			numberParameter("w5", 0, -4, 4),
			numberParameter("w6", 0, -4, 4),
			numberParameter("w7", 0, -4, 4),
			numberParameter("w8", 0, -4, 4),
			numberParameter("w9", 0, -4, 4),
			numberParameter("w10", 0, -4, 4),
			numberParameter("w11", 0, -4, 4),
			numberParameter("w12", 0, -4, 4),
			numberParameter("w13", 0, -4, 4),
			numberParameter("w14", 0, -4, 4),
			numberParameter("w15", 0, -4, 4),
			numberParameter("w16", 0, -4, 4),
		),
		descriptor(
			"transformer", "Transformer", "Distortion", "generic",
			integerParameter("oversampling", 4, 2, 8),
			numberParameter("drive", 2.0, 0.1, 30),
			numberParameter("mix", 1.0, 0, 1),
			numberParameter("output", 1.0, 0, 4),
			numberParameter("highpassHz", 25, 5, sampleRate*0.45),
			numberParameter("dampingHz", 9000, 200, sampleRate*0.49),
			enumParameter("quality", "high", "high", "lightweight"),
		),
		descriptor(
			"widener", "Widener", "Spatial", "generic",
			numberParameter("mix", 0.5, 0, 1),
			numberParameter("width", 1, 0, 4),
		),
		descriptor(
			"phaser", "Phaser", "Modulation", "generic",
			numberParameter("minFreqHz", 300, 20, sampleRate*0.45),
			numberParameter("maxFreqHz", 1600, 21, sampleRate*0.49),
			integerParameter("stages", 6, 1, 6),
			numberParameter("rateHz", 0.4, 0.05, 5),
			numberParameter("feedback", 0.2, -0.99, 0.99),
			numberParameter("mix", 0.5, 0, 1),
		),
		descriptor(
			"tremolo", "Tremolo", "Modulation", "generic",
			numberParameter("rateHz", 4, 0.05, 20),
			numberParameter("depth", 0.6, 0, 1),
			numberParameter("smoothingMs", 5, 0, 200),
			numberParameter("mix", 1, 0, 1),
		),
		descriptor(
			"rotary", "Rotary", "Modulation", "generic",
			booleanParameter("fast", 0),
			numberParameter("mix", 1, 0, 1),
			numberParameter("drive", 1, 0.01, 10),
			numberParameter("stereoWidth", 1, 0, 1),
			numberParameter("crossoverHz", 800, 50, 12000),
		),
		descriptor(
			"delay", "Delay", "Time", "generic",
			numberParameter("time", 0.25, 0.001, 2),
			numberParameter("feedback", 0.35, 0, 0.99),
			numberParameter("mix", 0.25, 0, 1),
		),
		descriptor(
			"delay-simple", "Simple delay", "Time", "generic",
			numberParameter("delayMs", 20, 0, 500),
		),
		descriptor(
			"bass", "Bass", "Distortion", "generic",
			integerParameter("highpass", 0, 0, 2),
			numberParameter("frequency", 80, 10, 500),
			numberParameter("inputGain", 1, 0, 2),
			numberParameter("highGain", 1, 0, 2),
			numberParameter("original", 1, 0, 2),
			numberParameter("harmonic", 0, 0, 2),
			numberParameter("decay", 0, -1, 1),
			numberParameter("responseMs", 20, 1, 200),
		),
		descriptor(
			"pitch-time", "Time-domain pitch", "Pitch and spectral", "generic",
			numberParameter("sequence", 40, 20, 120),
			numberParameter("overlap", 10, 4, 60),
			numberParameter("semitones", 0, -24, 24),
			numberParameter("search", 15, 2, 40),
		),
		descriptor(
			"pitch-spectral", "Spectral pitch", "Pitch and spectral", "generic",
			integerParameter("frameSize", 1024, 256, 4096),
			numberParameter("hopRatio", 0.25, 0.01, 0.99),
			numberParameter("semitones", 0, -24, 24),
		),
		descriptor(
			"spectral-freeze", "Spectral Freeze", "Pitch and spectral", "generic",
			integerParameter("frameSize", 1024, 256, 4096),
			numberParameter("hopRatio", 0.25, 0.01, 0.99),
			booleanParameter("frozen", 1),
			numberParameter("mix", 1, 0, 1),
			enumParameter("phaseMode", "advance", "hold", "advance"),
		),
		descriptor(
			"granular", "Granular", "Pitch and spectral", "generic",
			numberParameter("grainSeconds", 0.08, 0.005, 0.5),
			numberParameter("overlap", 0.5, 0, 0.95),
			numberParameter("pitch", 1, 0.25, 4),
			numberParameter("spray", 0.1, 0, 1),
			numberParameter("baseDelay", 0.08, 0, 2),
			numberParameter("mix", 1, 0, 1),
		),
		descriptor(
			"reverb-freeverb", "Reverb Freeverb", "Time", "generic",
			numberParameter("wet", 0.22, 0, 1.5),
			numberParameter("dry", 1, 0, 1.5),
			numberParameter("roomSize", 0.72, 0, 0.98),
			numberParameter("damp", 0.45, 0, 0.99),
			numberParameter("gain", 0.015, 0, 0.1),
		),
		descriptor(
			"reverb-fdn", "Reverb Fdn", "Time", "generic",
			numberParameter("wet", 0.22, 0, 1.5),
			numberParameter("dry", 1, 0, 1.5),
			numberParameter("rt60", 1.8, 0.2, 8),
			numberParameter("preDelay", 0.01, 0, 0.1),
			numberParameter("damp", 0.45, 0, 0.99),
			numberParameter("modDepth", 0.002, 0, 0.01),
			numberParameter("modRate", 0.1, 0, 1),
		),
		descriptor(
			"reverb-conv", "Convolution reverb", "Time", "generic",
			integerParameter("irIndex", 0, 0, 2147483647),
			integerParameter("wet", 0.35, 0, 1),
		),
		descriptor(
			"dyn-compressor", "Compressor", "Dynamics", "dynamics",
			numberParameter("thresholdDB", -20, -60, 0),
			numberParameter("ratio", 4, 1, 100),
			numberParameter("kneeDB", 6, 0, 24),
			numberParameter("attackMs", 10, 0.1, 1000),
			numberParameter("releaseMs", 100, 1, 5000),
			numberParameter("makeupGainDB", 0, 0, 24),
			booleanParameter("autoMakeup", 0),
		),
		descriptor(
			"dyn-limiter", "Limiter", "Dynamics", "dynamics",
			numberParameter("thresholdDB", -0.1, -24, 0),
			numberParameter("releaseMs", 100, 1, 5000),
		),
		descriptor(
			"dyn-lookahead", "Lookahead limiter", "Dynamics", "dynamics",
			numberParameter("thresholdDB", -1, -24, 0),
			numberParameter("releaseMs", 100, 1, 5000),
			numberParameter("lookaheadMs", 3, 0, 200),
		),
		descriptor(
			"dyn-gate", "Gate", "Dynamics", "dynamics",
			numberParameter("thresholdDB", -40, -80, 0),
			numberParameter("ratio", 10, 1, 100),
			numberParameter("kneeDB", 6, 0, 24),
			numberParameter("attackMs", 0.1, 0.1, 1000),
			numberParameter("holdMs", 50, 0, 5000),
			numberParameter("releaseMs", 100, 1, 5000),
			numberParameter("rangeDB", -80, -120, 0),
		),
		descriptor(
			"dyn-expander", "Expander", "Dynamics", "dynamics",
			numberParameter("thresholdDB", -35, -80, 0),
			numberParameter("ratio", 2, 1, 100),
			numberParameter("kneeDB", 6, 0, 24),
			numberParameter("attackMs", 1, 0.1, 1000),
			numberParameter("releaseMs", 100, 1, 5000),
			numberParameter("rangeDB", -60, -120, 0),
			numberParameter("rmsWindowMs", 30, 1, 1000),
			enumParameter("topology", "feedforward", "feedforward", "feedback"),
			enumParameter("detector", "peak", "peak", "rms"),
		),
		descriptor(
			"dyn-deesser", "Deesser", "Dynamics", "generic",
			numberParameter("freqHz", 6000, 1000, sampleRate*0.49),
			numberParameter("q", 1.5, 0.1, 10),
			numberParameter("thresholdDB", -20, -80, 0),
			numberParameter("ratio", 4, 1, 100),
			numberParameter("kneeDB", 3, 0, 12),
			numberParameter("attackMs", 0.5, 0.01, 50),
			numberParameter("releaseMs", 20, 1, 500),
			numberParameter("rangeDB", -24, -60, 0),
			integerParameter("filterOrder", 2, 1, 4),
			booleanParameter("listen", 0),
			enumParameter("mode", "splitband", "splitband", "wideband"),
			enumParameter("detector", "bandpass", "bandpass", "highpass"),
		),
		descriptor(
			"dyn-transient", "Transient shaper", "Dynamics", "generic",
			numberParameter("attack", 0, -1, 1),
			numberParameter("sustain", 0, -1, 1),
			numberParameter("attackMs", 10, 0.1, 200),
			numberParameter("releaseMs", 120, 1, 2000),
		),
		descriptor(
			"dyn-multiband", "Multiband compressor", "Dynamics", "generic",
			integerParameter("bands", 3, 2, 3),
			integerParameter("order", 4, 2, 24),
			numberParameter("cross1Hz", 250, 40, sampleRate*0.2),
			numberParameter("cross2Hz", 3000, 140, sampleRate*0.45),
			numberParameter("lowThresholdDB", -20, -80, 0),
			numberParameter("lowRatio", 2.5, 1, 20),
			numberParameter("midThresholdDB", -18, -80, 0),
			numberParameter("midRatio", 3.0, 1, 20),
			numberParameter("highThresholdDB", -14, -80, 0),
			numberParameter("highRatio", 4.0, 1, 20),
			numberParameter("attackMs", 8, 0.1, 1000),
			numberParameter("releaseMs", 120, 1, 5000),
			numberParameter("kneeDB", 6, 0, 24),
			numberParameter("makeupGainDB", 0, 0, 24),
			booleanParameter("autoMakeup", 0),
		),
		descriptor(
			"vocoder", "Vocoder", "Modulation", "generic",
			numberParameter("attackMs", 0.5, 0.01, 100),
			numberParameter("releaseMs", 2.0, 0.01, 1000),
			numberParameter("inputLevel", 0, 0, 10),
			numberParameter("synthLevel", 0, 0, 10),
			numberParameter("vocoderLevel", 1, 0, 10),
		),
		descriptor(
			"reverb", "Reverb", "Time", "generic",
			numberParameter("wet", 0.22, 0, 1.5),
			numberParameter("dry", 1, 0, 1.5),
			numberParameter("roomSize", 0.72, 0, 0.98),
			numberParameter("damp", 0.45, 0, 0.99),
			numberParameter("gain", 0.015, 0, 0.1),
			numberParameter("rt60", 1.8, 0.2, 8),
			numberParameter("preDelay", 0.01, 0, 0.1),
			numberParameter("modDepth", 0.002, 0, 0.01),
			numberParameter("modRate", 0.1, 0, 1),
			enumParameter("model", "freeverb", "freeverb", "fdn"),
		),
		descriptor(
			"filter", "Filter", "Filters", "generic",
			numberParameter("freq", 1200, 20, sampleRate*0.49),
			numberParameter("gain", 0, -24, 24),
			numberParameter("q", 0.707, 0.2, 8),
			integerParameter("order", 2, 1, 16),
			enumParameter("family", "rbj", "rbj", "butterworth", "bessel", "chebyshev1", "chebyshev2", "elliptic", "moog"),
			enumParameter("kind", "lowpass", "lowpass", "highpass", "bandpass", "notch", "allpass", "peak", "lowshelf", "highshelf"),
		),
		descriptor(
			"filter-lowpass", "Filter Lowpass", "Filters", "generic",
			numberParameter("freq", 1200, 20, sampleRate*0.49),
			numberParameter("gain", 0, -24, 24),
			numberParameter("q", 0.707, 0.2, 8),
			integerParameter("order", 2, 1, 16),
			enumParameter("family", "rbj", "rbj", "butterworth", "bessel", "chebyshev1", "chebyshev2", "elliptic", "moog"),
			enumParameter("kind", "lowpass", "lowpass", "highpass", "bandpass", "notch", "allpass", "peak", "lowshelf", "highshelf"),
		),
		descriptor(
			"filter-highpass", "Filter Highpass", "Filters", "generic",
			numberParameter("freq", 1200, 20, sampleRate*0.49),
			numberParameter("gain", 0, -24, 24),
			numberParameter("q", 0.707, 0.2, 8),
			integerParameter("order", 2, 1, 16),
			enumParameter("family", "rbj", "rbj", "butterworth", "bessel", "chebyshev1", "chebyshev2", "elliptic", "moog"),
			enumParameter("kind", "highpass", "lowpass", "highpass", "bandpass", "notch", "allpass", "peak", "lowshelf", "highshelf"),
		),
		descriptor(
			"filter-bandpass", "Filter Bandpass", "Filters", "generic",
			numberParameter("freq", 1200, 20, sampleRate*0.49),
			numberParameter("gain", 0, -24, 24),
			numberParameter("q", 0.707, 0.2, 8),
			integerParameter("order", 2, 1, 16),
			enumParameter("family", "rbj", "rbj", "butterworth", "bessel", "chebyshev1", "chebyshev2", "elliptic", "moog"),
			enumParameter("kind", "bandpass", "lowpass", "highpass", "bandpass", "notch", "allpass", "peak", "lowshelf", "highshelf"),
		),
		descriptor(
			"filter-notch", "Filter Notch", "Filters", "generic",
			numberParameter("freq", 1200, 20, sampleRate*0.49),
			numberParameter("gain", 0, -24, 24),
			numberParameter("q", 0.707, 0.2, 8),
			integerParameter("order", 2, 1, 16),
			enumParameter("family", "rbj", "rbj", "butterworth", "bessel", "chebyshev1", "chebyshev2", "elliptic", "moog"),
			enumParameter("kind", "notch", "lowpass", "highpass", "bandpass", "notch", "allpass", "peak", "lowshelf", "highshelf"),
		),
		descriptor(
			"filter-allpass", "Filter Allpass", "Filters", "generic",
			numberParameter("freq", 1200, 20, sampleRate*0.49),
			numberParameter("gain", 0, -24, 24),
			numberParameter("q", 0.707, 0.2, 8),
			integerParameter("order", 2, 1, 16),
			enumParameter("family", "rbj", "rbj", "butterworth", "bessel", "chebyshev1", "chebyshev2", "elliptic", "moog"),
			enumParameter("kind", "allpass", "lowpass", "highpass", "bandpass", "notch", "allpass", "peak", "lowshelf", "highshelf"),
		),
		descriptor(
			"filter-peak", "Filter Peak", "Filters", "generic",
			numberParameter("freq", 1200, 20, sampleRate*0.49),
			numberParameter("gain", 0, -24, 24),
			numberParameter("q", 0.707, 0.2, 8),
			integerParameter("order", 2, 1, 16),
			enumParameter("family", "rbj", "rbj", "butterworth", "bessel", "chebyshev1", "chebyshev2", "elliptic", "moog"),
			enumParameter("kind", "peak", "lowpass", "highpass", "bandpass", "notch", "allpass", "peak", "lowshelf", "highshelf"),
		),
		descriptor(
			"filter-lowshelf", "Filter Lowshelf", "Filters", "generic",
			numberParameter("freq", 1200, 20, sampleRate*0.49),
			numberParameter("gain", 0, -24, 24),
			numberParameter("q", 0.707, 0.2, 8),
			integerParameter("order", 2, 1, 16),
			enumParameter("family", "rbj", "rbj", "butterworth", "bessel", "chebyshev1", "chebyshev2", "elliptic", "moog"),
			enumParameter("kind", "lowshelf", "lowpass", "highpass", "bandpass", "notch", "allpass", "peak", "lowshelf", "highshelf"),
		),
		descriptor(
			"filter-highshelf", "Filter Highshelf", "Filters", "generic",
			numberParameter("freq", 1200, 20, sampleRate*0.49),
			numberParameter("gain", 0, -24, 24),
			numberParameter("q", 0.707, 0.2, 8),
			integerParameter("order", 2, 1, 16),
			enumParameter("family", "rbj", "rbj", "butterworth", "bessel", "chebyshev1", "chebyshev2", "elliptic", "moog"),
			enumParameter("kind", "highshelf", "lowpass", "highpass", "bandpass", "notch", "allpass", "peak", "lowshelf", "highshelf"),
		),
		descriptor(
			"filter-moog", "Filter Moog", "Filters", "generic",
			numberParameter("freq", 1200, 20, sampleRate*0.49),
			numberParameter("gain", 0, -24, 24),
			numberParameter("q", 0.707, 0.2, 8),
			integerParameter("order", 8, 1, 16),
			enumParameter("family", "moog", "rbj", "butterworth", "bessel", "chebyshev1", "chebyshev2", "elliptic", "moog"),
			enumParameter("kind", "moog", "lowpass", "highpass", "bandpass", "notch", "allpass", "peak", "lowshelf", "highshelf"),
		),
	}
}
